services:
  analytics-service-api:
    image: phadkesharanmatrixcomsec/iva-workflow:analytics-service-api
    build:
      context: .
      dockerfile: ./src/AnalyticsService/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    restart: always
    networks:
      - iva-workflow-network

  camera-service-api:
    image: phadkesharanmatrixcomsec/iva-workflow:camera-service-api
    build:
      context: .
      dockerfile: ./src/CameraService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    restart: always
    networks:
      - iva-workflow-network

  iva-worker:
    image: phadkesharanmatrixcomsec/iva-workflow:iva-worker
    build:
      context: .
      dockerfile: ./src/IVAWorker/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    restart: always
    networks:
      - iva-workflow-network

  vehicle-management-service-api:
    image: phadkesharanmatrixcomsec/iva-workflow:vehicle-management-service-api
    build:
      context: .
      dockerfile: ./src/VehicleManagementService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    restart: always
    networks:
      - iva-workflow-network

networks:
  iva-workflow-network:
    driver: bridge
