apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service-api
  template:
    metadata:
      labels:
        app: analytics-service-api
    spec:
      containers:
      - name: analytics-service-api
        image: phadkesharanmatrixcomsec/iva-workflow:analytics-service-api-1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service-api-service
spec:
  selector:
    app: analytics-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

