apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-management-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-management-api
  template:
    metadata:
      labels:
        app: vehicle-management-api
    spec:
      containers:
      - name: vehicle-management-api
        image: phadkesharanmatrixcomsec/iva-workflow:vehicle-management-service-api
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-management-api-service
spec:
  selector:
    app: vehicle-management-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

